"""user_model

Revision ID: e107d0e5dbbd
Create Date: 2025-01-15 16:24:50.511865

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.common.enums import UserRoleEnum

# revision identifiers, used by Alembic.
revision: str = 'e107d0e5dbbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('username', sa.String(length=20), nullable=False),
        sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
        sa.Column('fullname', sa.String(length=30), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('role', sa.Enum(UserRoleEnum, name='userroleenum'), nullable=False),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute("DROP TYPE userroleenum")
    # ### end Alembic commands ###
